// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulaCred.Infrastructure.Contexts;

#nullable disable

namespace SimulaCred.Infrastructure.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulaCred.Domain.Entities.ProdutoInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("PrazoMaximo")
                        .HasColumnType("smallint");

                    b.Property<short>("PrazoMinimo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8220),
                            Nome = "Poupança Fácil Caixa",
                            PrazoMaximo = (short)6,
                            PrazoMinimo = (short)1,
                            Rentabilidade = 0.05m,
                            Risco = "MuitoBaixo",
                            Tipo = "Poupanca"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8220),
                            Nome = "CDB Caixa 2026",
                            PrazoMaximo = (short)12,
                            PrazoMinimo = (short)7,
                            Rentabilidade = 0.06m,
                            Risco = "MuitoBaixo",
                            Tipo = "Cdb"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8220),
                            Nome = "LCI Shopping Dia e Noite",
                            PrazoMaximo = (short)12,
                            PrazoMinimo = (short)1,
                            Rentabilidade = 0.10m,
                            Risco = "Baixo",
                            Tipo = "Lci"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8220),
                            Nome = "LCA Comida na Mesa",
                            PrazoMaximo = (short)24,
                            PrazoMinimo = (short)13,
                            Rentabilidade = 0.12m,
                            Risco = "Baixo",
                            Tipo = "Lca"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8220),
                            Nome = "Imovel Legal Caixa",
                            PrazoMaximo = (short)60,
                            PrazoMinimo = (short)24,
                            Rentabilidade = 0.13m,
                            Risco = "Moderado",
                            Tipo = "Imoveis"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8230),
                            Nome = "Fundo XPTO",
                            PrazoMaximo = (short)48,
                            PrazoMinimo = (short)12,
                            Rentabilidade = 0.15m,
                            Risco = "Moderado",
                            Tipo = "Fundo"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8230),
                            Nome = "Ações Tabajara LTDA",
                            PrazoMinimo = (short)1,
                            Rentabilidade = 0.16m,
                            Risco = "Alto",
                            Tipo = "Acoes"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8230),
                            Nome = "Tesouro Direto Caixa",
                            PrazoMaximo = (short)36,
                            PrazoMinimo = (short)12,
                            Rentabilidade = 0.18m,
                            Risco = "Alto",
                            Tipo = "TesouroDireto"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8230),
                            Nome = "Banco Master CDB",
                            PrazoMaximo = (short)12,
                            PrazoMinimo = (short)1,
                            Rentabilidade = 0.20m,
                            Risco = "Inadimplencia",
                            Tipo = "BancoMasterCdb"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 35, 44, 179, DateTimeKind.Utc).AddTicks(8230),
                            Nome = "Banco Master Precatórios",
                            PrazoMaximo = (short)24,
                            PrazoMinimo = (short)13,
                            Rentabilidade = 0.22m,
                            Risco = "Inadimplencia",
                            Tipo = "BancoMasterPrecatorios"
                        });
                });

            modelBuilder.Entity("SimulaCred.Domain.Entities.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrazoInvestimento")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("SimulaCred.Domain.Entities.Simulacao", b =>
                {
                    b.HasOne("SimulaCred.Domain.Entities.ProdutoInvestimento", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
